server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica2
  client:
    service-url:
      defaultZone: http://replica1:8002/eureka # replica 需要配置host
    fetch-registry: true
    register-with-eureka: true